### ISSUE TITLE
Doc looks weird

### ISSUE THREAD

**Issue by lf-araujo** [FedericoCeratto/nim-lmdb#1]
Hi @FedericoCeratto just a heads up, documentation for this package looks weird:

![image](https://user-images.githubusercontent.com/10139950/76354057-8cac5a00-62f0-11ea-9f21-99e93def7c50.png)

**Comment by FedericoCeratto** [comment]
Thanks!

**Comment by FedericoCeratto** [comment]
Related: https://github.com/nim-lang/Nim/issues/13638
